# Generated by Django 5.1.7 on 2025-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cw1app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professor",
            old_name="fname",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="professor",
            old_name="sname",
            new_name="surname",
        ),
        migrations.RenameField(
            model_name="taughtmodule",
            old_name="moduleid",
            new_name="module",
        ),
        migrations.RenameField(
            model_name="taughtmodule",
            old_name="proffessors",
            new_name="professors",
        ),
        migrations.AddField(
            model_name="professor",
            name="code",
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
