# Generated by Django 5.1.7 on 2025-03-10 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cw1app", "0003_remove_professor_rating_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaughtModule",
            new_name="ModuleInstance",
        ),
    ]
