# Generated by Django 5.1.7 on 2025-03-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cw1app", "0004_rename_taughtmodule_moduleinstance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="module",
        ),
        migrations.AddField(
            model_name="rating",
            name="moduleinstance",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="cw1app.moduleinstance",
            ),
            preserve_default=False,
        ),
    ]
